### ISSUE TITLE
Update deps?

### ISSUE THREAD

**Issue by wqwblock** [jacogr/substrate-ledger-ed25519#7]
Hi,

The default version of the utilities seem to be outdated from https://github.com/polkadot-js/common/releases

Should it be updated? Can make a PR for the same?

**Comment by jacogr** [comment]
Thjere has been no fundamental changes between the versions. Having said that, the next 8.4 release would swap to the upstream ss58 registry, https://github.com/paritytech/ss58-registry (or rather a package published from it, instead of pulling that data in) so at that point it would make sense.
